name: Build on push to main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    environment: docker

jobs:
  build-images-with-make:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: make up
      - uses: docker/login-action@v2
        name: Log in to docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}